services:
  adservice:
    build: ./src/adservice
    environment:
      - PORT=9555

  productcatalogservice:
    build: ./src/productcatalogservice
    environment:
      - PORT=3550
      - DISABLE_PROFILER=1

  cartservice:
    build: ./src/cartservice/src
    environment:
      - REDIS_ADDR=redis-cart:6379
    depends_on:
      - redis-cart

  redis-cart:
    image: redis:6-alpine

  shippingservice:
    build: ./src/shippingservice
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1

  currencyservice:
    build: ./src/currencyservice
    environment:
      - PORT=7000
      - DISABLE_PROFILER=1

  paymentservice:
    build: ./src/paymentservice
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1

  emailservice:
    build: ./src/emailservice
    environment:
      - PORT=8080
      - DISABLE_PROFILER=1

  recommendationservice:
    build: ./src/recommendationservice
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - DISABLE_PROFILER=1
    depends_on:
      - productcatalogservice

  checkoutservice:
    build: ./src/checkoutservice
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:8080
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
    depends_on:
      - productcatalogservice
      - shippingservice
      - paymentservice
      - emailservice
      - currencyservice
      - cartservice

  frontend:
    build: ./src/frontend
    ports:
      - "8000:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - ENABLE_PROFILER=0
      - SHOPPING_ASSISTANT_SERVICE_ADDR=shoppingassistantservice:8080
    depends_on:
      - productcatalogservice
      - currencyservice
      - cartservice
      - recommendationservice
      - shippingservice
      - checkoutservice
      - adservice

  loadgenerator:
    build: ./src/loadgenerator
    environment:
      - FRONTEND_ADDR=frontend:8080
    depends_on:
      - frontend